# Generated by Django 4.2.13 on 2026-09-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='reaction_type',
            field=models.CharField(choices=[('like', "👍 J'aime"), ('love', "❤️ J'adore"), ('haha', '😂 Haha'), ('wow', '😮 Waouh'), ('sad', '😢 Triste'), ('angry', '😡 En colère')], default='like', max_length=20),
        ),
    ]
