# Generated by Django 4.2.13 on 2026-09-15 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_like_reaction_type'),
        ('chat', '0002_message_is_read_messagerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_messages', to='posts.post'),
        ),
    ]
