# Generated by Django 4.2.13 on 2026-08-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='presentation',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre')], default='light', max_length=20),
        ),
    ]
