# Generated by Django 4.2.13 on 2026-08-20 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', "Demande d'ami"), ('friend_accepted', 'Demande acceptée'), ('new_post', 'Nouvelle publication'), ('comment', 'Commentaire'), ('like', "J'aime"), ('share', 'Partage')], max_length=30),
        ),
    ]
