# Generated by Django 4.2.13 on 2026-08-21 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('friend_request', "Demande d'ami"), ('friend_accepted', 'Demande acceptée'), ('new_post', 'Nouvelle publication'), ('comment', 'Commentaire'), ('like', "J'aime"), ('share', 'Partage'), ('message_request', 'Demande de message')], max_length=30),
        ),
    ]
