# Generated by Django 4.2.13 on 2026-08-21 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
        ('chat', '0002_message_is_read_messagerequest_and_more'),
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='friend_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='friends.friendrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.messagerequest'),
        ),
    ]
